//
// Generated by Bluespec Compiler (build 00185f79)
//
// On Sun Jan 23 17:01:01 IST 2022
//
//
// Ports:
// Name                         I/O  size props
// RDY_byte_in                    O     1 const
// byte_out                       O     8
// RDY_byte_out                   O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 unused
// byte_in_idx                    I     8
// byte_in_data                   I     8
// byte_out_idx                   I     8
// EN_byte_in                     I     1
//
// Combinational paths from inputs to outputs:
//   byte_out_idx -> byte_out
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module small_burst(CLK,
		   RST_N,

		   byte_in_idx,
		   byte_in_data,
		   EN_byte_in,
		   RDY_byte_in,

		   byte_out_idx,
		   byte_out,
		   RDY_byte_out);
  input  CLK;
  input  RST_N;

  // action method byte_in
  input  [7 : 0] byte_in_idx;
  input  [7 : 0] byte_in_data;
  input  EN_byte_in;
  output RDY_byte_in;

  // value method byte_out
  input  [7 : 0] byte_out_idx;
  output [7 : 0] byte_out;
  output RDY_byte_out;

  // signals for module outputs
  reg [7 : 0] byte_out;
  wire RDY_byte_in, RDY_byte_out;

  // register burst_in
  reg [2047 : 0] burst_in;
  wire [2047 : 0] burst_in$D_IN;
  wire burst_in$EN;

  // remaining internal signals
  reg [7 : 0] CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20,
	      CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19,
	      CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18,
	      CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17,
	      CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31,
	      CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30,
	      CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29,
	      CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27,
	      CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28,
	      CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26,
	      CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25,
	      CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24,
	      CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22,
	      CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32,
	      CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23,
	      CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21,
	      CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15,
	      CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12,
	      CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14,
	      CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10,
	      CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9,
	      CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11,
	      CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4,
	      CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13,
	      CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16,
	      CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6,
	      CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2,
	      CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1,
	      CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7,
	      CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3,
	      CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5,
	      CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8;
  wire [127 : 0] IF_byte_in_idx_SRL_4_EQ_0_84_THEN_IF_byte_in_i_ETC___d386,
		 IF_byte_in_idx_SRL_4_EQ_10_49_THEN_IF_byte_in__ETC___d351,
		 IF_byte_in_idx_SRL_4_EQ_11_46_THEN_IF_byte_in__ETC___d348,
		 IF_byte_in_idx_SRL_4_EQ_12_42_THEN_IF_byte_in__ETC___d344,
		 IF_byte_in_idx_SRL_4_EQ_13_39_THEN_IF_byte_in__ETC___d341,
		 IF_byte_in_idx_SRL_4_EQ_14_35_THEN_IF_byte_in__ETC___d337,
		 IF_byte_in_idx_SRL_4_EQ_15_THEN_IF_byte_in_idx_ETC___d334,
		 IF_byte_in_idx_SRL_4_EQ_1_81_THEN_IF_byte_in_i_ETC___d383,
		 IF_byte_in_idx_SRL_4_EQ_2_77_THEN_IF_byte_in_i_ETC___d379,
		 IF_byte_in_idx_SRL_4_EQ_3_74_THEN_IF_byte_in_i_ETC___d376,
		 IF_byte_in_idx_SRL_4_EQ_4_70_THEN_IF_byte_in_i_ETC___d372,
		 IF_byte_in_idx_SRL_4_EQ_5_67_THEN_IF_byte_in_i_ETC___d369,
		 IF_byte_in_idx_SRL_4_EQ_6_63_THEN_IF_byte_in_i_ETC___d365,
		 IF_byte_in_idx_SRL_4_EQ_7_60_THEN_IF_byte_in_i_ETC___d362,
		 IF_byte_in_idx_SRL_4_EQ_8_56_THEN_IF_byte_in_i_ETC___d358,
		 IF_byte_in_idx_SRL_4_EQ_9_53_THEN_IF_byte_in_i_ETC___d355;
  wire [7 : 0] IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
	       IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
	       x__h1789,
	       x__h39805,
	       x__h39832;

  // action method byte_in
  assign RDY_byte_in = 1'd1 ;

  // value method byte_out
  always@(x__h39832 or
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 or
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 or
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 or
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 or
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 or
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 or
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 or
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 or
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 or
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 or
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 or
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 or
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 or
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 or
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 or
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16)
  begin
    case (x__h39832)
      8'd0: byte_out = CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1;
      8'd1: byte_out = CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2;
      8'd2: byte_out = CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3;
      8'd3: byte_out = CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4;
      8'd4: byte_out = CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5;
      8'd5: byte_out = CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6;
      8'd6: byte_out = CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7;
      8'd7: byte_out = CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8;
      8'd8: byte_out = CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9;
      8'd9:
	  byte_out = CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10;
      8'd10:
	  byte_out = CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11;
      8'd11:
	  byte_out = CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12;
      8'd12:
	  byte_out = CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13;
      8'd13:
	  byte_out = CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14;
      8'd14:
	  byte_out = CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15;
      8'd15:
	  byte_out = CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16;
      default: byte_out = 8'b10101010 /* unspecified value */ ;
    endcase
  end
  assign RDY_byte_out = 1'd1 ;

  // register burst_in
  assign burst_in$D_IN =
	     { IF_byte_in_idx_SRL_4_EQ_15_THEN_IF_byte_in_idx_ETC___d334,
	       IF_byte_in_idx_SRL_4_EQ_14_35_THEN_IF_byte_in__ETC___d337,
	       IF_byte_in_idx_SRL_4_EQ_13_39_THEN_IF_byte_in__ETC___d341,
	       IF_byte_in_idx_SRL_4_EQ_12_42_THEN_IF_byte_in__ETC___d344,
	       IF_byte_in_idx_SRL_4_EQ_11_46_THEN_IF_byte_in__ETC___d348,
	       IF_byte_in_idx_SRL_4_EQ_10_49_THEN_IF_byte_in__ETC___d351,
	       IF_byte_in_idx_SRL_4_EQ_9_53_THEN_IF_byte_in_i_ETC___d355,
	       IF_byte_in_idx_SRL_4_EQ_8_56_THEN_IF_byte_in_i_ETC___d358,
	       IF_byte_in_idx_SRL_4_EQ_7_60_THEN_IF_byte_in_i_ETC___d362,
	       IF_byte_in_idx_SRL_4_EQ_6_63_THEN_IF_byte_in_i_ETC___d365,
	       IF_byte_in_idx_SRL_4_EQ_5_67_THEN_IF_byte_in_i_ETC___d369,
	       IF_byte_in_idx_SRL_4_EQ_4_70_THEN_IF_byte_in_i_ETC___d372,
	       IF_byte_in_idx_SRL_4_EQ_3_74_THEN_IF_byte_in_i_ETC___d376,
	       IF_byte_in_idx_SRL_4_EQ_2_77_THEN_IF_byte_in_i_ETC___d379,
	       IF_byte_in_idx_SRL_4_EQ_1_81_THEN_IF_byte_in_i_ETC___d383,
	       IF_byte_in_idx_SRL_4_EQ_0_84_THEN_IF_byte_in_i_ETC___d386 } ;
  assign burst_in$EN = EN_byte_in ;

  // remaining internal signals
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 =
	     (byte_in_idx[3:0] == 4'd0) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126 =
	     (byte_in_idx[3:0] == 4'd10) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106 =
	     (byte_in_idx[3:0] == 4'd11) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85 =
	     (byte_in_idx[3:0] == 4'd12) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65 =
	     (byte_in_idx[3:0] == 4'd13) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44 =
	     (byte_in_idx[3:0] == 4'd14) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24 =
	     (byte_in_idx[3:0] == 4'd15) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311 =
	     (byte_in_idx[3:0] == 4'd1) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290 =
	     (byte_in_idx[3:0] == 4'd2) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270 =
	     (byte_in_idx[3:0] == 4'd3) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249 =
	     (byte_in_idx[3:0] == 4'd4) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229 =
	     (byte_in_idx[3:0] == 4'd5) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208 =
	     (byte_in_idx[3:0] == 4'd6) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188 =
	     (byte_in_idx[3:0] == 4'd7) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167 =
	     (byte_in_idx[3:0] == 4'd8) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 ;
  assign IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147 =
	     (byte_in_idx[3:0] == 4'd9) ?
	       byte_in_data :
	       CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 ;
  assign IF_byte_in_idx_SRL_4_EQ_0_84_THEN_IF_byte_in_i_ETC___d386 =
	     (x__h1789 == 8'd0) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[127:0] ;
  assign IF_byte_in_idx_SRL_4_EQ_10_49_THEN_IF_byte_in__ETC___d351 =
	     (x__h1789 == 8'd10) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[1407:1280] ;
  assign IF_byte_in_idx_SRL_4_EQ_11_46_THEN_IF_byte_in__ETC___d348 =
	     (x__h1789 == 8'd11) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[1535:1408] ;
  assign IF_byte_in_idx_SRL_4_EQ_12_42_THEN_IF_byte_in__ETC___d344 =
	     (x__h1789 == 8'd12) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[1663:1536] ;
  assign IF_byte_in_idx_SRL_4_EQ_13_39_THEN_IF_byte_in__ETC___d341 =
	     (x__h1789 == 8'd13) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[1791:1664] ;
  assign IF_byte_in_idx_SRL_4_EQ_14_35_THEN_IF_byte_in__ETC___d337 =
	     (x__h1789 == 8'd14) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[1919:1792] ;
  assign IF_byte_in_idx_SRL_4_EQ_15_THEN_IF_byte_in_idx_ETC___d334 =
	     (x__h1789 == 8'd15) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[2047:1920] ;
  assign IF_byte_in_idx_SRL_4_EQ_1_81_THEN_IF_byte_in_i_ETC___d383 =
	     (x__h1789 == 8'd1) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[255:128] ;
  assign IF_byte_in_idx_SRL_4_EQ_2_77_THEN_IF_byte_in_i_ETC___d379 =
	     (x__h1789 == 8'd2) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[383:256] ;
  assign IF_byte_in_idx_SRL_4_EQ_3_74_THEN_IF_byte_in_i_ETC___d376 =
	     (x__h1789 == 8'd3) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[511:384] ;
  assign IF_byte_in_idx_SRL_4_EQ_4_70_THEN_IF_byte_in_i_ETC___d372 =
	     (x__h1789 == 8'd4) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[639:512] ;
  assign IF_byte_in_idx_SRL_4_EQ_5_67_THEN_IF_byte_in_i_ETC___d369 =
	     (x__h1789 == 8'd5) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[767:640] ;
  assign IF_byte_in_idx_SRL_4_EQ_6_63_THEN_IF_byte_in_i_ETC___d365 =
	     (x__h1789 == 8'd6) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[895:768] ;
  assign IF_byte_in_idx_SRL_4_EQ_7_60_THEN_IF_byte_in_i_ETC___d362 =
	     (x__h1789 == 8'd7) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[1023:896] ;
  assign IF_byte_in_idx_SRL_4_EQ_8_56_THEN_IF_byte_in_i_ETC___d358 =
	     (x__h1789 == 8'd8) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[1151:1024] ;
  assign IF_byte_in_idx_SRL_4_EQ_9_53_THEN_IF_byte_in_i_ETC___d355 =
	     (x__h1789 == 8'd9) ?
	       { IF_byte_in_idx_BITS_3_TO_0_EQ_15_THEN_byte_in__ETC___d24,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_14_5_THEN_byte_i_ETC___d44,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_13_6_THEN_byte_i_ETC___d65,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_12_6_THEN_byte_i_ETC___d85,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_11_7_THEN_byte_i_ETC___d106,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_10_07_THEN_byte__ETC___d126,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_9_28_THEN_byte_i_ETC___d147,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_8_48_THEN_byte_i_ETC___d167,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_7_69_THEN_byte_i_ETC___d188,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_6_89_THEN_byte_i_ETC___d208,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_5_10_THEN_byte_i_ETC___d229,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_4_30_THEN_byte_i_ETC___d249,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_3_51_THEN_byte_i_ETC___d270,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_2_71_THEN_byte_i_ETC___d290,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_1_92_THEN_byte_i_ETC___d311,
		 IF_byte_in_idx_BITS_3_TO_0_EQ_0_12_THEN_byte_i_ETC___d331 } :
	       burst_in[1279:1152] ;
  assign x__h1789 = byte_in_idx >> 4 ;
  assign x__h39805 = { 4'd0, byte_out_idx[3:0] } ;
  assign x__h39832 = byte_out_idx >> 4 ;
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[415:408];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[423:416];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[551:544];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[543:536];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[535:528];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[407:400];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[279:272];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[287:280];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[479:472];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[487:480];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[615:608];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[607:600];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[599:592];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[471:464];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[343:336];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
	      burst_in[351:344];
      default: CASE_x9805_0_burst_in_BITS_415_TO_408_1_burst__ETC__q1 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[295:288];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[303:296];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[431:424];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[559:552];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[687:680];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[679:672];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[671:664];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[663:656];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[359:352];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[367:360];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[495:488];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[623:616];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[751:744];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[743:736];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[735:728];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
	      burst_in[727:720];
      default: CASE_x9805_0_burst_in_BITS_295_TO_288_1_burst__ETC__q2 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[655:648];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[527:520];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[399:392];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[271:264];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[143:136];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[151:144];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[159:152];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[167:160];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[719:712];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[591:584];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[463:456];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[335:328];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[207:200];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[215:208];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[223:216];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
	      burst_in[231:224];
      default: CASE_x9805_0_burst_in_BITS_655_TO_648_1_burst__ETC__q3 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[175:168];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[183:176];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[311:304];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[439:432];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[567:560];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[695:688];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[823:816];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[815:808];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[239:232];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[247:240];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[375:368];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[503:496];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[631:624];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[759:752];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[887:880];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
	      burst_in[879:872];
      default: CASE_x9805_0_burst_in_BITS_175_TO_168_1_burst__ETC__q4 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[807:800];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[799:792];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[791:784];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[783:776];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[775:768];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[647:640];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[519:512];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[391:384];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[871:864];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[863:856];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[855:848];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[847:840];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[839:832];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[711:704];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[583:576];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
	      burst_in[455:448];
      default: CASE_x9805_0_burst_in_BITS_807_TO_800_1_burst__ETC__q5 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[263:256];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[135:128];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[7:0];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[15:8];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[23:16];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[31:24];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[39:32];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[47:40];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[327:320];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[199:192];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[71:64];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[79:72];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[87:80];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[95:88];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[103:96];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
	      burst_in[111:104];
      default: CASE_x9805_0_burst_in_BITS_263_TO_256_1_burst__ETC__q6 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[55:48];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[63:56];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[191:184];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[319:312];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[447:440];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[575:568];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[703:696];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[831:824];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[119:112];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[127:120];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[255:248];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[383:376];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[511:504];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[639:632];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[767:760];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
	      burst_in[895:888];
      default: CASE_x9805_0_burst_in_BITS_55_TO_48_1_burst_in_ETC__q7 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[959:952];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[951:944];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[943:936];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[935:928];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[927:920];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[919:912];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[911:904];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[903:896];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[1023:1016];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[1015:1008];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[1007:1000];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[999:992];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[991:984];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[983:976];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[975:968];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
	      burst_in[967:960];
      default: CASE_x9805_0_burst_in_BITS_959_TO_952_1_burst__ETC__q8 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1439:1432];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1447:1440];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1575:1568];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1567:1560];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1559:1552];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1431:1424];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1303:1296];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1311:1304];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1503:1496];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1511:1504];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1639:1632];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1631:1624];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1623:1616];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1495:1488];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1367:1360];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
	      burst_in[1375:1368];
      default: CASE_x9805_0_burst_in_BITS_1439_TO_1432_1_burs_ETC__q9 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1319:1312];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1327:1320];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1455:1448];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1583:1576];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1711:1704];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1703:1696];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1695:1688];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1687:1680];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1383:1376];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1391:1384];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1519:1512];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1647:1640];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1775:1768];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1767:1760];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1759:1752];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
	      burst_in[1751:1744];
      default: CASE_x9805_0_burst_in_BITS_1319_TO_1312_1_burs_ETC__q10 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1679:1672];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1551:1544];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1423:1416];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1295:1288];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1167:1160];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1175:1168];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1183:1176];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1191:1184];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1743:1736];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1615:1608];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1487:1480];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1359:1352];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1231:1224];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1239:1232];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1247:1240];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
	      burst_in[1255:1248];
      default: CASE_x9805_0_burst_in_BITS_1679_TO_1672_1_burs_ETC__q11 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1199:1192];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1207:1200];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1335:1328];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1463:1456];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1591:1584];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1719:1712];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1847:1840];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1839:1832];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1263:1256];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1271:1264];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1399:1392];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1527:1520];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1655:1648];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1783:1776];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1911:1904];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
	      burst_in[1903:1896];
      default: CASE_x9805_0_burst_in_BITS_1199_TO_1192_1_burs_ETC__q12 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1831:1824];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1823:1816];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1815:1808];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1807:1800];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1799:1792];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1671:1664];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1543:1536];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1415:1408];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1895:1888];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1887:1880];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1879:1872];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1871:1864];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1863:1856];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1735:1728];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1607:1600];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
	      burst_in[1479:1472];
      default: CASE_x9805_0_burst_in_BITS_1831_TO_1824_1_burs_ETC__q13 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1287:1280];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1159:1152];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1031:1024];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1039:1032];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1047:1040];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1055:1048];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1063:1056];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1071:1064];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1351:1344];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1223:1216];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1095:1088];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1103:1096];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1111:1104];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1119:1112];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1127:1120];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
	      burst_in[1135:1128];
      default: CASE_x9805_0_burst_in_BITS_1287_TO_1280_1_burs_ETC__q14 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1079:1072];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1087:1080];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1215:1208];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1343:1336];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1471:1464];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1599:1592];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1727:1720];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1855:1848];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1143:1136];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1151:1144];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1279:1272];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1407:1400];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1535:1528];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1663:1656];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1791:1784];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
	      burst_in[1919:1912];
      default: CASE_x9805_0_burst_in_BITS_1079_TO_1072_1_burs_ETC__q15 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h39805 or burst_in)
  begin
    case (x__h39805)
      8'd0:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[1983:1976];
      8'd1:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[1975:1968];
      8'd2:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[1967:1960];
      8'd3:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[1959:1952];
      8'd4:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[1951:1944];
      8'd5:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[1943:1936];
      8'd6:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[1935:1928];
      8'd7:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[1927:1920];
      8'd8:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[2047:2040];
      8'd9:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[2039:2032];
      8'd10:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[2031:2024];
      8'd11:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[2023:2016];
      8'd12:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[2015:2008];
      8'd13:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[2007:2000];
      8'd14:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[1999:1992];
      8'd15:
	  CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
	      burst_in[1991:1984];
      default: CASE_x9805_0_burst_in_BITS_1983_TO_1976_1_burs_ETC__q16 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[127:120];
      8'd1:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[255:248];
      8'd2:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[383:376];
      8'd3:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[511:504];
      8'd4:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[639:632];
      8'd5:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[767:760];
      8'd6:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[895:888];
      8'd7:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[1023:1016];
      8'd8:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[1151:1144];
      8'd9:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[1279:1272];
      8'd10:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[1407:1400];
      8'd11:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[1535:1528];
      8'd12:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[1663:1656];
      8'd13:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[1791:1784];
      8'd14:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[1919:1912];
      8'd15:
	  CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
	      burst_in[2047:2040];
      default: CASE_x789_0_burst_in_BITS_127_TO_120_1_burst_i_ETC__q17 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[119:112];
      8'd1:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[247:240];
      8'd2:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[375:368];
      8'd3:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[503:496];
      8'd4:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[631:624];
      8'd5:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[759:752];
      8'd6:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[887:880];
      8'd7:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[1015:1008];
      8'd8:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[1143:1136];
      8'd9:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[1271:1264];
      8'd10:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[1399:1392];
      8'd11:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[1527:1520];
      8'd12:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[1655:1648];
      8'd13:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[1783:1776];
      8'd14:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[1911:1904];
      8'd15:
	  CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
	      burst_in[2039:2032];
      default: CASE_x789_0_burst_in_BITS_119_TO_112_1_burst_i_ETC__q18 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[111:104];
      8'd1:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[239:232];
      8'd2:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[367:360];
      8'd3:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[495:488];
      8'd4:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[623:616];
      8'd5:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[751:744];
      8'd6:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[879:872];
      8'd7:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[1007:1000];
      8'd8:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[1135:1128];
      8'd9:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[1263:1256];
      8'd10:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[1391:1384];
      8'd11:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[1519:1512];
      8'd12:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[1647:1640];
      8'd13:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[1775:1768];
      8'd14:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[1903:1896];
      8'd15:
	  CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
	      burst_in[2031:2024];
      default: CASE_x789_0_burst_in_BITS_111_TO_104_1_burst_i_ETC__q19 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[103:96];
      8'd1:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[231:224];
      8'd2:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[359:352];
      8'd3:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[487:480];
      8'd4:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[615:608];
      8'd5:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[743:736];
      8'd6:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[871:864];
      8'd7:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[999:992];
      8'd8:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[1127:1120];
      8'd9:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[1255:1248];
      8'd10:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[1383:1376];
      8'd11:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[1511:1504];
      8'd12:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[1639:1632];
      8'd13:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[1767:1760];
      8'd14:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[1895:1888];
      8'd15:
	  CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
	      burst_in[2023:2016];
      default: CASE_x789_0_burst_in_BITS_103_TO_96_1_burst_in_ETC__q20 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[95:88];
      8'd1:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[223:216];
      8'd2:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[351:344];
      8'd3:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[479:472];
      8'd4:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[607:600];
      8'd5:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[735:728];
      8'd6:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[863:856];
      8'd7:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[991:984];
      8'd8:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[1119:1112];
      8'd9:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[1247:1240];
      8'd10:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[1375:1368];
      8'd11:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[1503:1496];
      8'd12:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[1631:1624];
      8'd13:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[1759:1752];
      8'd14:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[1887:1880];
      8'd15:
	  CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
	      burst_in[2015:2008];
      default: CASE_x789_0_burst_in_BITS_95_TO_88_1_burst_in__ETC__q21 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[79:72];
      8'd1:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[207:200];
      8'd2:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[335:328];
      8'd3:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[463:456];
      8'd4:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[591:584];
      8'd5:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[719:712];
      8'd6:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[847:840];
      8'd7:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[975:968];
      8'd8:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[1103:1096];
      8'd9:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[1231:1224];
      8'd10:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[1359:1352];
      8'd11:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[1487:1480];
      8'd12:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[1615:1608];
      8'd13:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[1743:1736];
      8'd14:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[1871:1864];
      8'd15:
	  CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
	      burst_in[1999:1992];
      default: CASE_x789_0_burst_in_BITS_79_TO_72_1_burst_in__ETC__q22 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[87:80];
      8'd1:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[215:208];
      8'd2:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[343:336];
      8'd3:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[471:464];
      8'd4:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[599:592];
      8'd5:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[727:720];
      8'd6:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[855:848];
      8'd7:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[983:976];
      8'd8:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[1111:1104];
      8'd9:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[1239:1232];
      8'd10:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[1367:1360];
      8'd11:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[1495:1488];
      8'd12:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[1623:1616];
      8'd13:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[1751:1744];
      8'd14:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[1879:1872];
      8'd15:
	  CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
	      burst_in[2007:2000];
      default: CASE_x789_0_burst_in_BITS_87_TO_80_1_burst_in__ETC__q23 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[71:64];
      8'd1:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[199:192];
      8'd2:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[327:320];
      8'd3:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[455:448];
      8'd4:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[583:576];
      8'd5:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[711:704];
      8'd6:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[839:832];
      8'd7:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[967:960];
      8'd8:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[1095:1088];
      8'd9:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[1223:1216];
      8'd10:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[1351:1344];
      8'd11:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[1479:1472];
      8'd12:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[1607:1600];
      8'd13:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[1735:1728];
      8'd14:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[1863:1856];
      8'd15:
	  CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
	      burst_in[1991:1984];
      default: CASE_x789_0_burst_in_BITS_71_TO_64_1_burst_in__ETC__q24 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[63:56];
      8'd1:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[191:184];
      8'd2:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[319:312];
      8'd3:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[447:440];
      8'd4:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[575:568];
      8'd5:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[703:696];
      8'd6:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[831:824];
      8'd7:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[959:952];
      8'd8:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[1087:1080];
      8'd9:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[1215:1208];
      8'd10:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[1343:1336];
      8'd11:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[1471:1464];
      8'd12:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[1599:1592];
      8'd13:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[1727:1720];
      8'd14:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[1855:1848];
      8'd15:
	  CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
	      burst_in[1983:1976];
      default: CASE_x789_0_burst_in_BITS_63_TO_56_1_burst_in__ETC__q25 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[55:48];
      8'd1:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[183:176];
      8'd2:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[311:304];
      8'd3:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[439:432];
      8'd4:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[567:560];
      8'd5:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[695:688];
      8'd6:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[823:816];
      8'd7:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[951:944];
      8'd8:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[1079:1072];
      8'd9:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[1207:1200];
      8'd10:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[1335:1328];
      8'd11:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[1463:1456];
      8'd12:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[1591:1584];
      8'd13:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[1719:1712];
      8'd14:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[1847:1840];
      8'd15:
	  CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
	      burst_in[1975:1968];
      default: CASE_x789_0_burst_in_BITS_55_TO_48_1_burst_in__ETC__q26 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[39:32];
      8'd1:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[167:160];
      8'd2:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[295:288];
      8'd3:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[423:416];
      8'd4:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[551:544];
      8'd5:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[679:672];
      8'd6:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[807:800];
      8'd7:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[935:928];
      8'd8:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[1063:1056];
      8'd9:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[1191:1184];
      8'd10:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[1319:1312];
      8'd11:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[1447:1440];
      8'd12:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[1575:1568];
      8'd13:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[1703:1696];
      8'd14:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[1831:1824];
      8'd15:
	  CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
	      burst_in[1959:1952];
      default: CASE_x789_0_burst_in_BITS_39_TO_32_1_burst_in__ETC__q27 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[47:40];
      8'd1:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[175:168];
      8'd2:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[303:296];
      8'd3:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[431:424];
      8'd4:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[559:552];
      8'd5:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[687:680];
      8'd6:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[815:808];
      8'd7:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[943:936];
      8'd8:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[1071:1064];
      8'd9:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[1199:1192];
      8'd10:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[1327:1320];
      8'd11:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[1455:1448];
      8'd12:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[1583:1576];
      8'd13:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[1711:1704];
      8'd14:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[1839:1832];
      8'd15:
	  CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
	      burst_in[1967:1960];
      default: CASE_x789_0_burst_in_BITS_47_TO_40_1_burst_in__ETC__q28 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[31:24];
      8'd1:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[159:152];
      8'd2:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[287:280];
      8'd3:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[415:408];
      8'd4:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[543:536];
      8'd5:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[671:664];
      8'd6:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[799:792];
      8'd7:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[927:920];
      8'd8:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[1055:1048];
      8'd9:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[1183:1176];
      8'd10:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[1311:1304];
      8'd11:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[1439:1432];
      8'd12:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[1567:1560];
      8'd13:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[1695:1688];
      8'd14:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[1823:1816];
      8'd15:
	  CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
	      burst_in[1951:1944];
      default: CASE_x789_0_burst_in_BITS_31_TO_24_1_burst_in__ETC__q29 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[23:16];
      8'd1:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[151:144];
      8'd2:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[279:272];
      8'd3:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[407:400];
      8'd4:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[535:528];
      8'd5:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[663:656];
      8'd6:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[791:784];
      8'd7:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[919:912];
      8'd8:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[1047:1040];
      8'd9:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[1175:1168];
      8'd10:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[1303:1296];
      8'd11:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[1431:1424];
      8'd12:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[1559:1552];
      8'd13:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[1687:1680];
      8'd14:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[1815:1808];
      8'd15:
	  CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
	      burst_in[1943:1936];
      default: CASE_x789_0_burst_in_BITS_23_TO_16_1_burst_in__ETC__q30 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[15:8];
      8'd1:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[143:136];
      8'd2:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[271:264];
      8'd3:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[399:392];
      8'd4:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[527:520];
      8'd5:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[655:648];
      8'd6:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[783:776];
      8'd7:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[911:904];
      8'd8:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[1039:1032];
      8'd9:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[1167:1160];
      8'd10:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[1295:1288];
      8'd11:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[1423:1416];
      8'd12:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[1551:1544];
      8'd13:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[1679:1672];
      8'd14:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[1807:1800];
      8'd15:
	  CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
	      burst_in[1935:1928];
      default: CASE_x789_0_burst_in_BITS_15_TO_8_1_burst_in_B_ETC__q31 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(x__h1789 or burst_in)
  begin
    case (x__h1789)
      8'd0:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[7:0];
      8'd1:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[135:128];
      8'd2:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[263:256];
      8'd3:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[391:384];
      8'd4:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[519:512];
      8'd5:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[647:640];
      8'd6:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[775:768];
      8'd7:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[903:896];
      8'd8:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[1031:1024];
      8'd9:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[1159:1152];
      8'd10:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[1287:1280];
      8'd11:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[1415:1408];
      8'd12:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[1543:1536];
      8'd13:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[1671:1664];
      8'd14:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[1799:1792];
      8'd15:
	  CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
	      burst_in[1927:1920];
      default: CASE_x789_0_burst_in_BITS_7_TO_0_1_burst_in_BI_ETC__q32 =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (burst_in$EN) burst_in <= `BSV_ASSIGNMENT_DELAY burst_in$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    burst_in =
	2048'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // small_burst

